name: zamstay_app
description: ZedStay - Accommodation Discovery and Booking Platform for Zambia
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^14.6.3

  # Supabase (database + auth + storage)
  supabase_flutter: ^2.9.1

  # HTTP client
  dio: ^5.8.0+1

  # Local storage / offline cache
  hive_flutter: ^1.1.0

  # Secure storage (for JWT tokens)
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.3.2

  # Image handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1

  # Internationalisation
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

  # Utilities
  equatable: ^2.0.5
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.1


flutter:
  uses-material-design: true
  generate: true